FROM node:gallium-alpine3.13 AS frontBuild

LABEL stage=build
RUN apk --no-cache add git
RUN git clone https://github.com/barais/doodlestudent.git /app --depth=1

WORKDIR /app/front
RUN npm i
RUN npx ng build --prod

FROM nginx:stable-alpine

COPY --from=frontBuild /app/front/dist/tlcfront /usr/share/nginx/html
COPY --from=frontBuild /app/front/nginx/hosts /etc/
