FROM maven:3-adoptopenjdk-11 as apiBuild

LABEL stage=build
WORKDIR /app/build

COPY . .
RUN mvn clean package -Dquarkus.package.type=uber-jar

FROM adoptopenjdk/openjdk11
COPY --from=apiBuild /app/build/target/tlcdemoApp-1.0.0-SNAPSHOT-runner.jar /app/
ENTRYPOINT java -jar /app/tlcdemoApp-1.0.0-SNAPSHOT-runner.jar